### ISSUE TITLE
Error when trying to use .withLatestFrom inside effects of a component

### ISSUE THREAD

**Issue by brec-c** [recyclejs/recycle#19]
I'm really new to this library and Rxjs in general but I haven't found any answer searching through the source.  

I'm getting:
`Header.js:25 Uncaught TypeError: e.select(...).addListener(...).withLatestFrom is not a function`

in browser console.  I have no idea why, my example is about as vanilla as it gets.  

Where does `withLatestFrom` come from?  Rxjs?  

Stepping through in debugger it seems that for whatever reason what is returned from `addListener` does not include a `withLatestFrom` function.  The call to ref.stream.switch() returns an AnonymousSubject for whatever that's worth to you.

**Comment by brec-c** [comment]
Figured it out.  You have to add `import Rx from 'rxjs'` even if not directly using rx.

**Comment by domagojk** [comment]
@brec-c ```import Rx from 'rxjs'``` imports "the entire core set of functionality" which is why it works for you.
If you want to keep smaller size of your bundle and import only what you need, you have to use something like this:
```
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/map';
```

For more info on this check [rxjs docs](https://github.com/ReactiveX/rxjs)
