### ISSUE TITLE
Typescript support??

### ISSUE THREAD

**Issue by edunuzzi** [recyclejs/recycle#22]
I am thinking about using this amazing lib into my next project and i would like to hear about your thoughts about supporting typescript. It shouldn't be that hard to do so, and i would be willing to put some effort myself and create a pull a request, if you are ok with it ;)

**Comment by domagojk** [comment]
What kind of support exactly do you have in mind?
Of course, feel free to send your pull request! :)

**Comment by edunuzzi** [comment]
A simple index.d.ts would be enough for me. 
Awesome! Tomorrow i will start digging into the implementation to make sure i don't miss anything :)

**Comment by domagojk** [comment]
I've merged your pull request and published it to npm :)
Closing this issue for now...
